### DISCUSSION TITLE
v2.0.2

### DISCUSSION THREAD

**Discussion by gri38** [joplin-vieweb/joplin-vieweb#8] [Announcements]
# Issues fixed
#3 : Missing docker-compose-joplin-only.yml file
You can read the documentation in the [README](https://github.com/joplin-vieweb/joplin-vieweb/blob/main/README.md#installation--configuration-instructions).
# Docker images:
## new 
* django-joplin-vieweb: v2.0.2
## same
* joplin-terminal-xapi: v2.0.0
* joplin-vieweb-nginx: v2.0.0
* joplin-vieweb-certbot: v2.0.0
# Upgrade
```diff
- If you had a previous install, you must upgrade your docker-compose.yaml file
- to add scheme (http:// or https:// to the ORIGINS common variables.
- Also add port if applicable for your setup.
```
For instance:
```yaml
x-common-variables: &common-variables
   ORIGINS: "'https://your_domain.com', 'https://12.34.56.78'"
   CERT_DOMAIN: your_domain.com 
   CERT_MAIL: you@zaclys.net
```
* go to the folder of your docker-compose file
```bash
sudo docker-compose down
sudo docker-compose pull
sudo docker-compose up
```

<hr /><em>This discussion was created from the release <a href='https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.0.2'>v2.0.2</a>.</em>
