### ISSUE TITLE
Missing docker-compose-joplin-only.yml file

### ISSUE THREAD

**Issue by tpbraini** [joplin-vieweb/joplin-vieweb#3]
Any hints for Joplin only  configuration.

Leaving away...

-joplin nginx viewweb
-certbot

...doesn*t work for me,

joplin-vieweb-django-joplin-vieweb-1  | Configuring endpoint tcp:port=8001:interface=127.0.0.1
joplin-vieweb-django-joplin-vieweb-1  | Listening on TCP address 127.0.0.1:8001
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by kestr31** [comment]
- That's similar with my initial purpose
  - Since I use external proxy manager, I had to configure like that
- As suggested in the document, disabling nginx & certbot container helped
- Moreover, if you use external proxy manager to be connected to localhost, localhost must be added to ORIGINS
<br/>

- Following is a working sample of docker-compose I'm currently using I hope this can help:

```yaml
version: '3.4'

x-common-variables: &common-variables
   ORIGINS: "'domain.com', 'ext_ip', 'localhost'"

services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:latest
    depends_on:
      - joplin-terminal-xapi
    environment:
       <<: *common-variables
    restart: unless-stopped
    volumes:
      - joplin:/root/.config/joplin:ro
      - joplin-vieweb:/root/.config/joplin-vieweb
      - certbot_www:/var/www/certbot/:ro
    networks:
      - YOUR-NETWORK
    ports:
      - <PORT_TO_PROXY_MNGR>:8000

  joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:latest
    restart: unless-stopped
    volumes:
      - joplin:/root/.config/joplin
    networks:
      - YOUR-NETWORK

#  joplin-vieweb-certbot:
#    image: gri38/joplin-vieweb-certbot:latest
#    restart: unless-stopped
#    environment:
#       <<: *common-variables
#    depends_on:
#      - joplin-vieweb-nginx
#    volumes:
#      - certbot_www:/var/www/certbot/:rw
#      - certbot_conf:/etc/letsencrypt/:rw

#  joplin-vieweb-nginx:
#    image: gri38/joplin-vieweb-nginx:latest
#    restart: unless-stopped
#    ports:
#      - 80:80
#      - 443:443
#    environment:
#       <<: *common-variables
#    volumes:
#      - certbot_www:/var/www/certbot/:ro
#      - certbot_conf:/etc/letsencrypt/:ro
#    networks:
#      - YOUR-NETWORK

volumes:
  joplin:
  joplin-vieweb:
  certbot_www:
  certbot_conf:

networks:
  YOUR-NETWORK:
    external: true
```

**Comment by tpbraini** [comment]
Thanks for you reply. 
My YML look quite similar.

I just want to use it in my local network. 
Running it in a Proxmox container.

It always stucks on "Listening to TCP adress...."

**Comment by kestr31** [comment]
I think that it's not a problem of joplin vieweb I just tested another configuration by adding server's local ip in `ORIGIN` so that it can be added in `ALLOWED_HOSTS`

For example, if I wan't to connect to `http://192.168.178.162:port/joplin`, I set `ORIGIN` like:

```yaml
x-common-variables: &common-variables
   ORIGINS: "''192.168.178.162`'"
```

After then, I could access Joplin-vieweb in local network.

For what I undertand, this can be a solution for you. Is this right?

**Comment by gri38** [comment]
Hello.

I'm glad you use the project.
I added the docker-compose file without certbot stuff.

@kestr31 you were right. 
2 differences: 

1. I write the ORIGINS like that:

```yaml
x-common-variables: &common-variables
   ORIGINS: "'localhost', '192.168.21.1'"
```

2. I didn't add
```yaml
networks:
  YOUR-NETWORK:
    external: true
```
Do you think it's required ? It worked without for me... 

But **it won't work directly** because the [django CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins) are built from origins like that: 
"https://" + origin

So trusted origins will be, in my example:
http**s**://localhost  
http**s**://192.168.21.1  
And it should be, I think:
http://localhost  
http://192.168.21.1  
Another way it may fail: if you access with a port, let say 8080, the origin would be 
http://192.168.21.1:8080, which is not in trusted origin (:8080 is not !)

@tpbraini couls you please explin your conf.
For testing purpose I can publish an image dedicated to you config.

I think the solution should be to set the origins like that:
For internal access:
```yaml
x-common-variables: &common-variables
   ORIGINS: "'http://localhost:1234', 'http://192.168.21.1:1234'"
```
For external access:
```yaml
x-common-variables: &common-variables
   ORIGINS: "'https://domain:1234', 'https://11.22.33.44:1234'"
```
But usually for extrenal access it will be the standard https port, not written in url, so we should configure like that:
```yaml
x-common-variables: &common-variables
   ORIGINS: "'https://domain', 'https://11.22.33.44'"
```

Let me know about yuor conf, I'll implement the parse of scheme://address[:port]

**Comment by gri38** [comment]
Hi 

I tried some changes: could you try please to use:
* the docker compose file [here](https://github.com/joplin-vieweb/joplin-vieweb/blob/dev_issue_3/docker-compose-joplin-only.yml)
* and you change it: 
  * set your port in <PORT-TO-YOUR-PROXY>
  * adapt the ORIGINS (the change is I added http:// to the origins). If you use a specific port, for instance if you access with http://192.168.21.1:8000/joplin, you should set the port in the ORIGINS.
  * Change the image tage for django-joplin-vieweb:
```yaml
services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:2.0.2-4
``` 

It works for me, but I still have issues with settings (get conf fails: I'll have a look to that but for the moment let me know if it's better for you).
