### ISSUE TITLE
Sync does not work for WebDAV

### ISSUE THREAD

**Issue by djcastaldo** [joplin-vieweb/joplin-vieweb#33]
This is so promising, but sync fails everytime.  Can you make this work for WebDAV servers?

**Comment by gri38** [comment]
I've just seen you closed this issue: why ?
We can see here [https://joplinapp.org/terminal/#webdav-synchronisation](https://joplinapp.org/terminal/#webdav-synchronisation) that webdav is similar but not the same conf as nextcloud.

**Comment by dbilee** [comment]
Great work, It's really looking forward to have this feature.

**Comment by gri38** [comment]
@dbilee That's good you wrote this comment because I'm not currently work on the project.
I'll try to implement webdav ASAP, if you're ok to test a version whith that feature it would help me.

**Comment by gri38** [comment]
Hi @dbilee 
I've just created 2 new docker images, could you please try to use them and let me know if you can synch with webdav.
I've tested the webdav sync config is well send and saved into joplin terminal, but I didn't test the synch with a true webdav server (I don't have one).

So: in your docker-compose.yml, could you please use the pre-release images:
```yaml
services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:2.3.0-1

[...]

joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:2.2.0-1

[...]
```

and let me know if it works.

Thanks.

**Comment by djcastaldo** [comment]
Hi, I previously closed the issue because I set up an instance of Joplin Server and now sync to that, which works fine with the vieweb app.

**Comment by dbilee** [comment]
> Hi @dbilee I've just created 2 new docker images, could you please try to use them and let me know if you can synch with webdav. I've tested the webdav sync config is well send and saved into joplin terminal, but I didn't test the synch with a true webdav server (I don't have one).
> 
> So: in your docker-compose.yml, could you please use the pre-release images:
> 
> ```yaml
> services:
>   django-joplin-vieweb:
>     image: gri38/django-joplin-vieweb:2.3.0-1
> 
> [...]
> 
> joplin-terminal-xapi:
>     image: gri38/joplin-terminal-xapi:2.2.0-1
> 
> [...]
> ```
> 
> and let me know if it works.
> 
> Thanks.

Thanks for your response, I've test it but failed, seems sth with environment : 
```log
/app/joplin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34
throw new Error(help.join('\n'));
^

Error:
Something went wrong installing the "sharp" module

Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /app/joplin/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp-linuxmusl-x64.node)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object. (/app/joplin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34:9)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object. (/app/joplin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:8:1)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.14.2
```

**Comment by gri38** [comment]
Hi  @dbilee 
Thanks for reporting.

That's not the change I did, but my new docker image containing joplin doesn't build anymore. 
I didn't freeze the versions... naughty boy! ;-)

I'll have to work a little bit so the docker image is okay again... I'll let you know.

**Comment by dbilee** [comment]
> Hi @dbilee Thanks for reporting.
> 
> That's not the change I did, but my new docker image containing joplin doesn't build anymore. I didn't freeze the versions... naughty boy! ;-)
> 
> I'll have to work a little bit so the docker image is okay again... I'll let you know.

OK, Thanks for your quick response

**Comment by gri38** [comment]
I've fixed it. Can you try again with V2.2.0-2 for joplin terminal xapi:
```yaml
services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:2.3.0-1

[...]

joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:2.2.0-2

[...]
```

**Comment by dbilee** [comment]
@gri38 tried with new version, but stuck with `Starting synchronisation...` the log shows:
```log
Synch finished: return code: 0
    status: 2023-03-11T14:04:35.528Z
    stdout: Synchronisation target:  (6)
Starting synchronisation...
Completed: 11/03/2023 14:04 (501s)
Downloading resources...

    stderr: 
```

I'm run [webdav](https://github.com/hacdias/webdav) on local machine

**Comment by gri38** [comment]
Hi.
thanks for testing.

It will be hard to debug without a webdav server... I'll try to se up one.
If you have any advice on how to do it easliy, I take.

Otherwise I think I'll try with https://hub.docker.com/r/bytemark/webdav/

**Comment by gri38** [comment]
Hi. I did some tests and finally make it work, without changing the code.

FYI, here is my docker-compose file for tests:
```yaml
version: '3.4'

x-common-variables: &common-variables
   ORIGINS: "'http://localhost:8000'"

services:
  django-joplin-vieweb:
    # image: gri38/django-joplin-vieweb:latest
    image: gri38/django-joplin-vieweb:2.3.0-1
    depends_on:
      - joplin-terminal-xapi
    environment:
       <<: *common-variables
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - joplin:/root/.config/joplin:ro
      - joplin-vieweb:/root/.config/joplin-vieweb
    networks:
      - joplin-net

  joplin-terminal-xapi:
    # image: gri38/joplin-terminal-xapi:latest
    image: gri38/joplin-terminal-xapi:2.2.0-2
    restart: unless-stopped
    volumes:
      - joplin:/root/.config/joplin
    networks:
      - joplin-net

  webdav.com:
    image: bytemark/webdav:latest
    restart: unless-stopped
    networks:
      - joplin-net
    environment:
      AUTH_TYPE: Basic
      USERNAME: bob
      PASSWORD: azerty
    ports:
      - 80:80

volumes:
  joplin:
  joplin-vieweb:

networks:
  joplin-net: {}
```

Here are some problems I had to overcome, maybe it will give you some clues:
### auth type
Joplin use Basic, so your webdav server must also be configured with Basic (not Digest)

### webdav server "hostname"
I don't know how do you run you webdav server. If like me you have a service in docker-compose file, this service must be on the **same network joplin-net** , and from joplin vieweb, the synchronisation url is not `http://localhost`, but the service name: **`http://webdav.com`** (with http://webdav, you'll have a "bad path error".

If your server is running outside docker, I make it work like that:
```yaml
services:
  django-joplin-vieweb:
    # ...
    networks:
      - joplin-net
      - host

# ...


networks:
  joplin-net: {}
  host: {}
```

And in joplin vieweb, I had to use the IP of my computer (http://192.168...) as url for webdav.

To debug, I attached a shell in the container of the service django-joplin-vieweb, and input some commands:
```bash
wget http://localhost 
# outputs:
# Connecting to localhost (127.0.0.1:80)
# wget: can't connect to remote host (127.0.0.1): Connection refused
# => doesn't work
wget http://myComputerHostname
# outputs:
# Connecting to gri-desktop (127.0.1.1:80)
# wget: can't connect to remote host (127.0.1.1): Connection refused
# => doesn't work
wget http://192.168.1.1
# outputs:
# Connecting to 192.168.21.1 (192.168.21.1:80)
# wget: server returned error: HTTP/1.1 401 Unauthorized
# => works
```


This should help you to make it work.
LEt me know
