### ISSUE TITLE
The requested resource was not found on this server.

### ISSUE THREAD

**Issue by Tiritibambix** [joplin-vieweb/joplin-vieweb#77]
Hello.

I'm running a Joplin server already so I used [docker-compose-joplin-only.yml](https://github.com/joplin-vieweb/joplin-vieweb/blob/main/docker-compose-joplin-only.yml)

I'm planning to use it locally only or through VPN tunnel.
My host machine is at 192.168.1.103
I also use permanent volumes and not docker volumes, so I commented the volumes part.
So here is my docker-compose:

```
version: '3.4'

x-common-variables: &common-variables
   ORIGINS: "'http://localhost', 'http://192.168.1.103'"
   JOPLIN_LOGIN_REQUIRED: True

services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:latest
    depends_on:
      - joplin-terminal-xapi
    environment:
       <<: *common-variables
    restart: unless-stopped
    ports:
      - 22301:8000
    volumes:
      - /srv/Files/JoplinWeb/joplin:/root/.config/joplin:ro
      - /srv/Files/JoplinWeb/joplin-vieweb:/root/.config/joplin-vieweb
    networks:
      - joplin-net

  joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:latest
    restart: unless-stopped
    volumes:
      - /srv/Files/JoplinWeb/joplin:/root/.config/joplin
    networks:
      - joplin-net

#volumes:
#  joplin:
#  joplin-vieweb:

networks:
  joplin-net: {}
```

When I go to http://192.168.1.103:22301, I get this error message: "NOT FOUND. The requested resource was not found on this server."

[Logs for terminal-xapi](https://clip.steph.click/-8eJbxWiM5j)
[Logs for vieweb](https://clip.steph.click/-MPcpRRDcrX)

I'm not sure what I'm doing wrong.

Can you help me please ?
Thank you.
